### ISSUE TITLE
这空间测绘也太牛了吧宝贝

### ISSUE THREAD

**Issue by kingofzihua** [levywang/random_web_player#1]
这个规则是日期索引啊，怎么保证的探测出来的都是视频资源呢宝贝？

**Comment by levywang** [comment]
去源站目录里面随便找个m3u8地址播放一下就知道了

**Comment by kingofzihua** [comment]
> 去源站目录里面随便找个m3u8地址播放一下就知道了

不是，他的这个规则是这样的
```
"<head><title>Index of /</title></head>" && "<a href=\"20230817/\">20230817/</a>"
```
用 fofa 也能查出一样的来

就是 nginx 中配置的目录列表，并且 有按照日期时间搜索的，这种大部分都是目录索引，只不过是正好命中了这个 m3u8的，这个正好命中可太神奇了。都算是特征码了，简直是牛逼

**Comment by levywang** [comment]
fofa用fid查询，特征码如下：

fid="iNDtdco4BknxHfX+8fCbBg==" || fid="hkdU5jzhVnKt/Bv3e1Ll1Q==" ||fid="lwOavR6ic3I2cv+M1sZ8Lg=="

**Comment by kingofzihua** [comment]
> fofa用fid查询，特征码如下：
> 
> fid="iNDtdco4BknxHfX+8fCbBg==" || fid="hkdU5jzhVnKt/Bv3e1Ll1Q==" ||fid="lwOavR6ic3I2cv+M1sZ8Lg=="

免费账户没有权限搜索fid字段
