### ISSUE TITLE
要是加上预览图的瀑布流就更好了

### ISSUE THREAD

**Issue by SuperBigYB** [levywang/random_web_player#2]

**Comment by levywang** [comment]
源站里面只有播放地址，没有其他信息，这个项目也不适合做后端存储，它只是一个"播放器"，需要保持它的纯净，如果做多了，会有一些不可抗阻力。

**Comment by SuperBigYB** [comment]
> 源站里面只有播放地址，没有其他信息，这个项目也不适合做后端存储，它只是一个"播放器"，需要保持它的纯净，如果做多了，会有一些不可抗阻力。

我看了一下, 源站里面很多是有图片的. 不可抗力这个确实, 做成客户端会不会保险一点

**Comment by levywang** [comment]
是个不错的想法，我考虑集成到api里，暂时先添加到todo里，这个issue关闭了

**Comment by levywang** [comment]
@SuperBigYB 最新版已添加该功能
